### Get all products
GET http://127.0.0.1:8000/products


### Create a new product
POST http://127.0.0.1:8000/products
Content-Type: application/json

{
"name" : "MacBook Pro",
"price" : 2800
}

### Get product by id
GET http://127.0.0.1:8000/products/1


### Update product by id
PUT http://127.0.0.1:8000/products/1

### Delete product by id
DELETE http://127.0.0.1:8000/products/1



### Get all orders
GET http://127.0.0.1:8000/orders


### Create a new orders
POST http://127.0.0.1:8000/orders
Content-Type: application/json

{
  "productId" : 1,
  "quantity" : 2
}

### Get orders by id
GET http://127.0.0.1:8000/orders/1

### Delete orders by id
DELETE http://127.0.0.1:8000/orders/1

###
